server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://fast-waiting.cny42waeivln.us-east-1.rds.amazonaws.com/fast_waiting
    username: admin
    password: 12345678
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 289929730693-kl9cp9lv08ndkga288mtoqp28n19ash9.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - email
#              - profile

  ##확장자를 머스테치로 바로 인식 가능하게 함
  #  mvc:
  #    view:
  #      prefix: /templates/
  #      suffix: .mustache

jpa:
  hibernate:
    ddl-auto: create #create update none
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  show-sql: true